### ISSUE TITLE
[Android 9] Odex and Vdex files generated, but the CRC32 verification fails.

### ISSUE THREAD

**Issue by xihan123** [giacomoferretti/odex-patcher#8]
It does not work on Android P. Although odex and vdex are generated, the crc32 verification fails. It is useless to close selinux.

**Comment by giacomoferretti** [comment]
Sorry to hear that :disappointed:, could you provide me more information like:
* App's version
* Device manufacturer (Pixel, Samsung, etc.)
* ROM (Stock, AOSP, TouchWiz, etc.) 
* Original APK and modded apk (optional)
* Logcat (optional)

**Comment by xihan123** [comment]
1.1.1.2
2.OPPO R11
3.ROM：https://mega.nz/file/XdtT1SZT#Qio4VgXe9RxoI-b_d71Jf81r7lj_4LBlvp4yz_BYKrw
4.apk：https://mega.nz/folder/zZ8VwaSS#9xBYrKQ8xWTD04IEiBSeTg

**Comment by giacomoferretti** [comment]
Uninstall the app and reinstall it. After that send me the output of these commands:
```bash
adb shell
su
ls -lZ /data/app/com.xihan.demo-SOMETHING/
```
I want to check if the original odex files are generated before patching. If not, try this command:
```
adb shell
su
chmod 777 /data/app/com.xihan.demo-SOMETHING/oat/ARCHITECTURE/*
```

**Comment by xihan123** [comment]
R11:/ # ls -lZ /data/app/com.xihan.demo-l40Hr0vDJXjWTDOpXA8nKQ==
total 24
-rw-r--r-- 1 system system  u:object_r:apk_data_file:s0         14923 2020-12-25 01:51 base.apk
drwxr-xr-x 2 system system  u:object_r:apk_data_file:s0          4096 2020-12-25 01:51 lib
drwxrwx--x 3 system install u:object_r:dalvikcache_data_file:s0  4096 2020-12-25 01:51 oat

**Comment by giacomoferretti** [comment]
Output of this command? `ls -lZ /data/app/com.xihan.demo-l40Hr0vDJXjWTDOpXA8nKQ==/oat/arm64/`

**Comment by xihan123** [comment]
R11:/ # ls -lZ /data/app/com.xihan.demo-l40Hr0vDJXjWTDOpXA8nKQ==/oat/arm64/
total 32
-rw-r----- 1 system all_a319 u:object_r:dalvikcache_data_file:s0  8192 2020-12-25 01:51 base.art
-rw-r----- 1 system all_a319 u:object_r:dalvikcache_data_file:s0 17304 2020-12-25 01:51 base.odex
-rw-r----- 1 system all_a319 u:object_r:dalvikcache_data_file:s0  2636 2020-12-25 01:51 base.vdex

**Comment by giacomoferretti** [comment]
So these are the original ones? Can you send me a copy of these?
Try to patch and rerun the command, and send me the files. Thank you for you help!

**Comment by xihan123** [comment]
https://mega.nz/file/6csVSara#c11nAA_H56y_WEer6s1jBhAuhE9-jzsxj447TQDR-80

**Comment by giacomoferretti** [comment]
Where did you see the error? Can you send me the logcat when you launch the application?

**Comment by xihan123** [comment]
After patching, the app does not take effect after starting the app, the same is true for closing selinux and restarting the phone. My phone cannot see logcat, system limitation

**Comment by giacomoferretti** [comment]
Ok no problem. I'm gonna checkout the files.

**Comment by giacomoferretti** [comment]
Last thing: can you run `adb shell getprop dalvik.vm.check-dex-sum`?

**Comment by xihan123** [comment]
No, it's blank after running

**Comment by giacomoferretti** [comment]
Ok, perfect. Thank you

**Comment by xihan123** [comment]
Is there a solution, the conclusion is that ColorOS 5+ (Android 8.1+) does not support it?

**Comment by giacomoferretti** [comment]
I've tested from Android 4.4 to 11 in emulators and sometimes on real devices, usually running AOSP. The patched checksum seems fine, so the causes that come to my mind are:
1) Possible permission error (SELinux, owner and group)
2) Not patching the `boot.art` file
3) Something in ColorOS that I'm not aware of (unlikely)

**Comment by xihan123** [comment]
After patching, the crc32 checksum I saw in the MT manager changed. Trying to delete .art is useless, forget it, I gave up. I still use Hook. thank you for your help!

**Comment by giacomoferretti** [comment]
Which CRC32 is MT Manager showing?

**Comment by xihan123** [comment]
I mean that the CRC32 check value before and after the patch is different

**Comment by giacomoferretti** [comment]
Yeah, but the checksum of the file itself or the OAT checksum?

**Comment by xihan123** [comment]
The check value of odex and vdex, if the crc32 check value is the same before and after patching, I think it can pass selinux

**Comment by giacomoferretti** [comment]
@xihan123 sorry to bother you, but I probably found the cause. It didn't work correctly on 64bit. Can you give it another try when I push an update?

**Comment by xihan123** [comment]
> @xihan123很抱歉打扰您，但我可能找到了原因。它在 64 位上无法正常工作。当我推送更新时，您可以再试一次吗？

**Comment by giacomoferretti** [comment]
Can you try this? https://github.com/giacomoferretti/odex-patcher/releases/tag/v2.0.0-rc1

If you encounter any problem, press the "Report" button in the top area of the app and paste it here.

**Comment by xihan123** [comment]
> 你能试试这个吗？https://github.com/giacomoferretti/odex-patcher/releases/tag/v2.0.0-rc1
> 
> 如果您遇到任何问题，请按应用程序顶部区域的“报告”按钮并将其粘贴到此处。

Beautiful, my previous demo test passed, thank you

**Comment by giacomoferretti** [comment]
Thank you!
